# Generated by Django 4.2.14 on 2024-12-23 16:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_category_id_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('592b2ec3-e6b6-4a54-b250-8e3f782492f8'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='color',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5d88ef8d-4773-484d-a32e-9e202645d73f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('032f86ab-4bf7-4e80-ba9e-9843e7033915'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8217cc87-22e3-4706-9559-e2112942bceb'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='size',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4799c4e7-0b0b-4ca8-b171-3fa2de30d3ab'), primary_key=True, serialize=False),
        ),
    ]
