# Generated by Django 4.2.14 on 2024-12-23 16:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_id_alter_color_id_alter_image_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5d476bb7-627d-42da-ad05-e03654803681'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='color',
            name='id',
            field=models.UUIDField(default=uuid.UUID('460d8c17-618b-4f26-a0db-565b5ee1db40'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('35dbeb75-8954-4a1d-a131-0ca822a89921'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='product.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('935477c3-e0f9-4dd9-9280-f417b2e54ad4'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='size',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b21971fb-fc58-4093-a0d5-472f04c92657'), primary_key=True, serialize=False),
        ),
    ]
