# Generated by Django 4.2.14 on 2024-12-23 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_id_alter_color_id_alter_image_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='product.product'),
        ),
    ]
